name = "view-counter"

compatibility_date = "2023-10-16"
main = "index.js"

workers_dev = true

[[d1_databases]]
binding = "ViewCounter" # i.e. available in your Worker on env.DB
database_id = "72f5fd97-3f01-40e7-b31f-6c3117a9c624" 
database_name = "ViewCounter"
